Dz 2
belorusochkayul/Android pull request #3
Opened 2021-03-13 17:01 UTC by belorusochkayul

2021-03-13 19:58 UTC, tim-teacher requested changes

2021-03-13 19:58 UTC, tim-teacher commented on AndroidBeginner/app/src/main/java/com/example/firstandroid/MenuActivity.java
> +                    }
ммм, так. Что то тут походы ты скопировала с предыдущего ДЗ)))). Во первых в этой активити не нужно создавать переменные вверху (строка 12).
Нам нужно найти кнопку findViewById и установить клик на него, по лику нужно открывать нужную активити. Все это задается в onCreate, другие методы не нужны. 

И еще, а зачем тебе доступ к переменным `ScrollView` и `LinearLayout`? Они нигде не используются и в строке 22 видно что ты их сама создаешь. Похоже что случайно эксперементировала и забыла удалить :).

2021-04-10 17:33 UTC, belorusochkayul commented
Привет! Поправила: activity_menu.xml и MenuActivity, AndroidManifest

2021-04-11 21:33 UTC, tim-teacher approved these changes

2021-04-12 08:44 UTC, merged